# Menu
menu:
  首页: /
  归档: /archives
  # Gallery: /gallery
  关于: /about
  友链: /about/friend.html
rss: /atom.xml


# Miscellaneous
favicon: /images/favicon1.ico
brand: /images/head_2.png

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: http://source.zhwangart.com/hexo/themes/ocean/video/
  brand: /images/hexo-inverted.svg

# Content
excerpt_link: 阅读更多
nav_prev_text: 上一篇...
nav_next_text: ...下一篇
share_text: 分享文章

# fancybox
fancybox: true

# RSS
# feed:
#   type: atom
#   path: atom.xml
#   limit: 20
#   hub:
#   content:
#   content_limit: 140
#   content_limit_delim: ' '
#   order_by: -date

# Local search
search_text: 搜索
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  unescape: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID
